CREATE TABLE "USUARIOS" (
  "ID" INTEGER,
  "NOME" TEXT NOT NULL,
  "SENHA" TEXT NOT NULL,
  "DATA_CRIACAO" TEXT DEFAULT(CURRENT_TIMESTAMP),
  PRIMARY KEY("ID")
);

CREATE TABLE "SALDO_CC" (
    "ID" INTEGER,
    "ID_USUARIO" INTEGER,
    "VALOR" REAL CHECK("VALOR" >= 0),
    "DATA_ATUALIZACAO" TEXT DEFAULT(CURRENT_TIMESTAMP),
    PRIMARY KEY("ID"),
    FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID")
);

CREATE TABLE "SALDO_CP" (
    "ID" INTEGER,
    "ID_USUARIO" INTEGER,
    "VALOR" REAL CHECK("VALOR" >= 0),
    "DATA_ATUALIZACAO" TEXT DEFAULT(CURRENT_TIMESTAMP),
    PRIMARY KEY("ID"),
    FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID")
);

CREATE TABLE "TRANSACOES_CC" (
  "ID" INTEGER,
  "ID_USUARIO" INTEGER,
  "ID_CATEGORIA" INTEGER,
  "TIPO" INTEGER NOT NULL CHECK("TIPO" IN (0,1)),
  "VALOR" REAL CHECK("VALOR" >= 0),
  "DATA" TEXT DEFAULT(CURRENT_TIMESTAMP),
  PRIMARY KEY("ID"),
  FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID"),
  FOREIGN KEY("ID_CATEGORIA") REFERENCES "CATEGORIAS"("ID")
);

CREATE TABLE "TRANSACOES_CP" (
  "ID" INTEGER,
  "ID_USUARIO" INTEGER,
  "TIPO" INTEGER NOT NULL CHECK("TIPO" IN (0,1)),
  "VALOR" REAL CHECK("VALOR" >= 0),
  "DATA" TEXT DEFAULT(CURRENT_TIMESTAMP),
  PRIMARY KEY("ID"),
  FOREIGN KEY("ID_USUARIO") REFERENCES "USUARIOS"("ID")
);

CREATE TABLE "CATEGORIAS" (
  "ID" INTEGER,
  "NOME" TEXT NOT NULL UNIQUE,
  "DESCRICAO" TEXT DEFAULT "-",
  PRIMARY KEY("ID")
);